# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Voltaire
email: hello@voltaire.ninja
description: > # this means to ignore newlines until "baseurl:"
  Voltaire es un lugar de trabajo, un grupo de amigos y un catalizador de proyectos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://voltaire.ninja" # the base hostname & protocol for your site
twitter_username: voltairehacks
github_username:  voltairehacks

# Build settings
markdown: kramdown
